### ISSUE TITLE
moa-plugin-user 模块缺少 middlewares 目录

### ISSUE THREAD

**Issue by zhongxia245** [moajs/moa-api#18]
```
mongodb://127.0.0.1:27017/moa-api
/Users/zhongxia/Code/nodejs/moa-frontend/app/middlewares
/Users/zhongxia/Code/nodejs/moa-frontend/app/middlewares
/Users/zhongxia/Code/nodejs/moa-frontend/app/controllers
/Users/zhongxia/Code/nodejs/moa-frontend/app/services
/Users/zhongxia/Code/nodejs/moa-frontend/node_modules/moa-plugin-user/app/controllers
/Users/zhongxia/Code/nodejs/moa-frontend/node_modules/moa-plugin-user/app/middlewares
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/zhongxia/Code/nodejs/moa-frontend/node_modules/moa-plugin-user/app/middlewares'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at requireDirectory (/Users/zhongxia/Code/nodejs/moa-frontend/node_modules/mount-middlewares/node_modules/require-directory/index.js:59:6)
    at m (/Users/zhongxia/Code/nodejs/moa-frontend/node_modules/mount-middlewares/index.js:14:10)
    at Object.<anonymous> (/Users/zhongxia/Code/nodejs/moa-frontend/node_modules/moa-plugin-user/app/routes/api/users.js:6:49)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at /Users/zhongxia/Code/nodejs/moa-frontend/node_modules/mount-routes/node_modules/require-directory/index.js:76:17
    at Array.forEach (native)
    at requireDirectory (/Users/zhongxia/Code/nodejs/moa-frontend/node_modules/mount-routes/node_modules/require-directory/index.js:59:24)
    at /Users/zhongxia/Code/nodejs/moa-frontend/node_modules/mount-routes/node_modules/require-directory/index.js:67:15
    at Array.forEach (native)
    at requireDirectory (/Users/zhongxia/Code/nodejs/moa-frontend/node_modules/mount-routes/node_modules/require-directory/index.js:59:24)
Program node ./bin/www exited with code 1

Starting child process with 'node ./bin/www'
log_path is exist, no operation!
```

**Comment by heliang1056** [comment]
我也遇到这个问题？不知道什么原因，希望解决
